import { join, resolve } from "node:path";

import { ensureDir, fileExists, runCommandCapture, writeStdout } from "../lib/base.ts";
import { HOOKS_TEMPLATE } from "../lib/hooks-template.ts";
import { c, icon } from "../lib/ui.ts";

const AEGIS_DIR = resolve(import.meta.dir, "../..");
const AEGIS_VERSION = (await Bun.file(join(AEGIS_DIR, "package.json")).json() as { version: string }).version;

const SHIM_CONTENT = `// Auto-generated by aegis install v${AEGIS_VERSION}. Do not edit.
// Observation-only mode: registers no hooks, blocks nothing.
export default async () => ({});
`;

const OPENCODE_PKG_CONTENT = JSON.stringify({ dependencies: { "aegis-security-agent": AEGIS_VERSION } }, null, 2) + "\n";

const ENV_SCHEMA_CONTENT = `# Aegis Security — Environment Schema
# Add your secrets here. Mark sensitive values with @sensitive.
# See https://varlock.dev for full syntax.
#
# Example:
# @sensitive
# MY_API_KEY=
`;

const PRE_COMMIT_CONFIG_CONTENT = `repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.82.13
    hooks:
      - id: trufflehog
        name: TruffleHog secret scan (Aegis)
        entry: trufflehog git file://. --since-commit HEAD --only-verified --fail
        language: system
        stages: [pre-commit]
`;

const TRUFFLEHOG_IGNORE_CONTENT = `# Auto-generated by aegis install. Excludes large binary paths that cause timeouts.
.git/objects/
.git/packed-refs
node_modules/
dist/
build/
*.lock
*.tar.gz
*.tar
*.zip
*.gz
*.whl
*.egg
`;

function log(status: "created" | "skipped" | "updated", filePath: string): void {
  const badge =
    status === "created" ? icon.pass :
    status === "updated" ? icon.info :
    c.dim("–");
  const label =
    status === "created" ? c.green("created") :
    status === "updated" ? c.cyan("updated") :
    c.dim("skipped");
  writeStdout(`  ${badge}  ${label}  ${c.dim(filePath)}\n`);
}

async function copyIfMissing(src: string, dest: string, force: boolean): Promise<void> {
  if (!force && await fileExists(dest)) {
    log("skipped", dest);
    return;
  }
  const existed = await fileExists(dest);
  const content = await Bun.file(src).text();
  await ensureDir(dest.substring(0, dest.lastIndexOf("/")));
  await Bun.write(dest, content);
  log(existed ? "updated" : "created", dest);
}

async function writeIfMissing(dest: string, content: string, force: boolean): Promise<void> {
  if (!force && await fileExists(dest)) {
    log("skipped", dest);
    return;
  }
  const existed = await fileExists(dest);
  await ensureDir(dest.substring(0, dest.lastIndexOf("/")));
  await Bun.write(dest, content);
  log(existed ? "updated" : "created", dest);
}

async function patchOpencodeJson(targetDir: string): Promise<void> {
  const configPath = join(targetDir, "opencode.json");
  let config: Record<string, unknown> = {};

  if (await fileExists(configPath)) {
    try {
      config = JSON.parse(await Bun.file(configPath).text()) as Record<string, unknown>;
    } catch {
      config = {};
    }
  }

  const plugins: string[] = Array.isArray(config["plugin"])
    ? (config["plugin"] as string[])
    : [];

  if (plugins.includes("aegis-security-agent")) {
    log("skipped", configPath + " (plugin already registered)");
    return;
  }

  config["plugin"] = [...plugins, "aegis-security-agent"];
  await Bun.write(configPath, JSON.stringify(config, null, 2) + "\n");
  log("updated", configPath);
}

async function installOpenCodeMode(targetDir: string, force: boolean): Promise<void> {
  await patchOpencodeJson(targetDir);

  await ensureDir(join(targetDir, ".aegis"));
  log("created", join(targetDir, ".aegis") + "/");

  const auditLogPath = join(targetDir, ".aegis", "audit.log");
  if (!await fileExists(auditLogPath)) {
    await Bun.write(auditLogPath, "");
    log("created", auditLogPath);
  }

  await copyIfMissing(
    join(AEGIS_DIR, "aegis-policy.json"),
    join(targetDir, "aegis-policy.json"),
    force,
  );

  // Always overwrite — this is a generated shim, not user-editable
  await writeIfMissing(
    join(targetDir, ".opencode", "plugins", "aegis.ts"),
    SHIM_CONTENT,
    true,
  );

  // Always overwrite — generated file, pins exact installed version
  await writeIfMissing(
    join(targetDir, ".opencode", "package.json"),
    OPENCODE_PKG_CONTENT,
    true,
  );

  // Always overwrite — generated agent definition, must stay in sync with package version
  const agentSrc = join(AEGIS_DIR, "docs", "agents", "aegis.md");
  if (await fileExists(agentSrc)) {
    const agentContent = (await Bun.file(agentSrc).text()).replaceAll("__AEGIS_DIR__", AEGIS_DIR);
    await writeIfMissing(
      join(targetDir, ".opencode", "agents", "aegis.md"),
      agentContent,
      true,
    );
  }

  await writeIfMissing(join(targetDir, ".env.schema"), ENV_SCHEMA_CONTENT, force);
  await writeIfMissing(join(targetDir, ".pre-commit-config.yaml"), PRE_COMMIT_CONFIG_CONTENT, force);
  // Always overwrite — excludes .git/objects/ to prevent TruffleHog timeouts
  await writeIfMissing(join(targetDir, ".trufflehogignore"), TRUFFLEHOG_IGNORE_CONTENT, true);

  // Remove npm lock file — it pins old versions and overrides bun on every OpenCode restart
  const opencodeDir = join(targetDir, ".opencode");
  const npmLock = join(opencodeDir, "package-lock.json");
  if (await fileExists(npmLock)) {
    await (await import("node:fs/promises")).rm(npmLock, { force: true });
    log("updated", npmLock + " (removed stale npm lock)");
  }

  // Update cached node_modules to ensure old intercepting versions are replaced
  if (await fileExists(join(opencodeDir, "package.json"))) {
    const updateResult = await runCommandCapture(["bun", "update", "aegis-security-agent"], { cwd: opencodeDir });
    if (updateResult.exitCode === 0) {
      writeStdout(`  ${icon.pass}  ${c.green("updated")}  ${c.dim(join(opencodeDir, "node_modules/aegis-security-agent"))}\n`);
    }
  }
}

async function installClaudeMode(targetDir: string, force: boolean): Promise<void> {
  const hooksContent = HOOKS_TEMPLATE.replaceAll("__AEGIS_DIR__", AEGIS_DIR);
  await writeIfMissing(join(targetDir, ".claude", "hooks.json"), hooksContent, force);

  await ensureDir(join(targetDir, ".aegis"));
  const auditLogPath = join(targetDir, ".aegis", "audit.log");
  if (!await fileExists(auditLogPath)) {
    await Bun.write(auditLogPath, "");
    log("created", auditLogPath);
  }

  const agentSrc = join(AEGIS_DIR, "docs", "agents", "aegis.md");
  const agentDest = join(targetDir, ".claude", "agents", "aegis.md");
  const agentContent = (await Bun.file(agentSrc).text()).replaceAll("__AEGIS_DIR__", AEGIS_DIR);
  await writeIfMissing(agentDest, agentContent, force);

  const claudeignoreSrc = join(AEGIS_DIR, ".claudeignore");
  const claudeignoreDest = join(targetDir, ".claudeignore");

  if (await fileExists(claudeignoreSrc)) {
    await copyIfMissing(claudeignoreSrc, claudeignoreDest, force);
  } else {
    await writeIfMissing(claudeignoreDest, "# Aegis — sensitive files\n.env\n.env.*\n**/*.pem\n**/*.key\n**/*_rsa\n", force);
  }

  // Always overwrite — excludes .git/objects/ to prevent TruffleHog timeouts
  await writeIfMissing(join(targetDir, ".trufflehogignore"), TRUFFLEHOG_IGNORE_CONTENT, true);
}

export async function runInstall(options: {
  targetDir: string;
  claude?: boolean;
  force?: boolean;
  skipDocker?: boolean;
}): Promise<number> {
  const { targetDir, claude = false, force = false, skipDocker = false } = options;

  writeStdout(`\n  ${icon.shield}  ${c.bold("Aegis Install")}  ${c.dim(targetDir)}\n\n`);

  if (!skipDocker) {
    // Non-blocking Docker check — just inform, don't fail
    const result = await runCommandCapture(["docker", "info"]);
    if (result.exitCode !== 0) {
      writeStdout(`  ${icon.warn}  ${c.yellow("Docker not available — degraded mode will be used at runtime")}\n\n`);
    }
  }

  try {
    if (claude) {
      await installClaudeMode(targetDir, force);
    } else {
      await installOpenCodeMode(targetDir, force);
    }

    writeStdout(`\n  ${icon.pass}  ${c.bold(c.green("Done."))}\n\n`);
    return 0;
  } catch (error) {
    process.stderr.write(`  ${icon.fail}  ${c.red("Install failed")}: ${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }
}
