import { join, resolve } from "node:path";

import { ensureDir, fileExists, runCommandCapture, writeStdout } from "../lib/base.ts";
import { HOOKS_TEMPLATE } from "../lib/hooks-template.ts";
import { c, icon } from "../lib/ui.ts";

const AEGIS_DIR = resolve(import.meta.dir, "../..");

const SHIM_CONTENT = `// Auto-generated by aegis install. Do not edit.
export { AegisSecurityPlugin as default } from "aegis-security-agent";
`;

const OPENCODE_PKG_CONTENT = JSON.stringify({ dependencies: { "aegis-security-agent": "latest" } }, null, 2) + "\n";

function log(status: "created" | "skipped" | "updated", filePath: string): void {
  const badge =
    status === "created" ? icon.pass :
    status === "updated" ? icon.info :
    c.dim("–");
  const label =
    status === "created" ? c.green("created") :
    status === "updated" ? c.cyan("updated") :
    c.dim("skipped");
  writeStdout(`  ${badge}  ${label}  ${c.dim(filePath)}\n`);
}

async function copyIfMissing(src: string, dest: string, force: boolean): Promise<void> {
  if (!force && await fileExists(dest)) {
    log("skipped", dest);
    return;
  }
  const existed = await fileExists(dest);
  const content = await Bun.file(src).text();
  await ensureDir(dest.substring(0, dest.lastIndexOf("/")));
  await Bun.write(dest, content);
  log(existed ? "updated" : "created", dest);
}

async function writeIfMissing(dest: string, content: string, force: boolean): Promise<void> {
  if (!force && await fileExists(dest)) {
    log("skipped", dest);
    return;
  }
  const existed = await fileExists(dest);
  await ensureDir(dest.substring(0, dest.lastIndexOf("/")));
  await Bun.write(dest, content);
  log(existed ? "updated" : "created", dest);
}

async function patchOpencodeJson(targetDir: string): Promise<void> {
  const configPath = join(targetDir, "opencode.json");
  let config: Record<string, unknown> = {};

  if (await fileExists(configPath)) {
    try {
      config = JSON.parse(await Bun.file(configPath).text()) as Record<string, unknown>;
    } catch {
      config = {};
    }
  }

  const plugins: string[] = Array.isArray(config["plugin"])
    ? (config["plugin"] as string[])
    : [];

  if (plugins.includes("aegis-security-agent")) {
    log("skipped", configPath + " (plugin already registered)");
    return;
  }

  config["plugin"] = [...plugins, "aegis-security-agent"];
  await Bun.write(configPath, JSON.stringify(config, null, 2) + "\n");
  log("updated", configPath);
}

async function installOpenCodeMode(targetDir: string, force: boolean): Promise<void> {
  await patchOpencodeJson(targetDir);

  await ensureDir(join(targetDir, ".aegis"));
  log("created", join(targetDir, ".aegis") + "/");

  await copyIfMissing(
    join(AEGIS_DIR, "aegis-policy.json"),
    join(targetDir, "aegis-policy.json"),
    force,
  );

  await writeIfMissing(
    join(targetDir, ".opencode", "plugins", "aegis.ts"),
    SHIM_CONTENT,
    force,
  );

  await writeIfMissing(
    join(targetDir, ".opencode", "package.json"),
    OPENCODE_PKG_CONTENT,
    force,
  );

  // Agent definition — enables @aegis in the OpenCode agent picker
  const agentSrc = join(AEGIS_DIR, "docs", "agents", "aegis.md");
  if (await fileExists(agentSrc)) {
    const agentContent = (await Bun.file(agentSrc).text()).replaceAll("__AEGIS_DIR__", AEGIS_DIR);
    await writeIfMissing(
      join(targetDir, ".opencode", "agents", "aegis.md"),
      agentContent,
      force,
    );
  }
}

async function installClaudeMode(targetDir: string, force: boolean): Promise<void> {
  const hooksContent = HOOKS_TEMPLATE.replaceAll("__AEGIS_DIR__", AEGIS_DIR);
  await writeIfMissing(join(targetDir, ".claude", "hooks.json"), hooksContent, force);

  const agentSrc = join(AEGIS_DIR, "docs", "agents", "aegis.md");
  const agentDest = join(targetDir, ".claude", "agents", "aegis.md");

  if (!force && await fileExists(agentDest)) {
    log("skipped", agentDest);
  } else {
    const agentContent = (await Bun.file(agentSrc).text()).replaceAll("__AEGIS_DIR__", AEGIS_DIR);
    const existed = await fileExists(agentDest);
    await ensureDir(join(targetDir, ".claude", "agents"));
    await Bun.write(agentDest, agentContent);
    log(existed ? "updated" : "created", agentDest);
  }

  const claudeignoreSrc = join(AEGIS_DIR, ".claudeignore");
  const claudeignoreDest = join(targetDir, ".claudeignore");

  if (await fileExists(claudeignoreSrc)) {
    await copyIfMissing(claudeignoreSrc, claudeignoreDest, force);
  } else {
    await writeIfMissing(claudeignoreDest, "# Aegis — sensitive files\n.env\n.env.*\n**/*.pem\n**/*.key\n**/*_rsa\n", force);
  }
}

export async function runInstall(options: {
  targetDir: string;
  claude?: boolean;
  force?: boolean;
  skipDocker?: boolean;
}): Promise<number> {
  const { targetDir, claude = false, force = false, skipDocker = false } = options;

  writeStdout(`\n  ${icon.shield}  ${c.bold("Aegis Install")}  ${c.dim(targetDir)}\n\n`);

  if (!skipDocker) {
    // Non-blocking Docker check — just inform, don't fail
    const result = await runCommandCapture(["docker", "info"]);
    if (result.exitCode !== 0) {
      writeStdout(`  ${icon.warn}  ${c.yellow("Docker not available — degraded mode will be used at runtime")}\n\n`);
    }
  }

  try {
    if (claude) {
      await installClaudeMode(targetDir, force);
    } else {
      await installOpenCodeMode(targetDir, force);
    }

    writeStdout(`\n  ${icon.pass}  ${c.bold(c.green("Done."))}\n\n`);
    return 0;
  } catch (error) {
    process.stderr.write(`  ${icon.fail}  ${c.red("Install failed")}: ${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }
}
